name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install autotools (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

      - name: Install dependencies
        run: make

      - name: Check linting
        run: make lint

      - name: Run test
        run: make test
